To get started do the following:

Download and unzip the source or clone the following GitHub repository:

[source, bash]
----
git clone https://github.com/micronaut-guides/micronaut-maven-azure.git
----

This Micronaut guide contains two folders:

- `initial` Initial project. A simple Micronaut app as you may have created with Micronaut CLI.``

- `complete` A completed example. It is the result of working through the steps presented by the guide and applying those changes to the initial folder.

To complete the guide, go to the initial folder

`cd initial`

and follow the instructions in the next sections.

or you can go right to the completed example:

`cd complete`

Although you can go right to the completed example, in order to deploy the app you
would need to complete several configuration steps in Microsoft Azure:

- Install the https://docs.microsoft.com/cli/azure/install-azure-cli?view=azure-cli-latest?WT.mc_id=opensource-micronaut-brborges[Azure CLI]

- https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?WT.mc_id=opensource-micronaut-brborges&view=azure-cli-latest#sign-in-interactively[Authenticate] with your Azure account

After you've checked out the links above, follow below for the next steps on setting up the Maven plugin for Azure deployment.
